### ISSUE TITLE
Link at the end of a sentence adds an extra space before full stop

### ISSUE THREAD

**Issue by jokroese** [JulianCataldo/web-garden#70]
I've really enjoyed using the different components here. Thanks @JulianCataldo for sharing them!

## Issue

I'm having an issue with the `<Link>` component. When I use it at the end of a sentence, it adds a space between the link and the full stop. E.g. "This is the link ."

## Example

(I can make a full MRE if it's helpful.) 

### Code

```html
<p>
  This is fine when the <Link href="/somewhere">link</Link> is not at the end of the sentence.
</p>
<p>
  But there is an issue when the sentence finishes with a <Link href="/somewhere">link</Link>.
</p>
<p>
  Everything is fine when I have a normal <a href="/somewhere">link</a>.
</p>
```

### Result

<img width="500" alt="Screenshot 2023-01-07 at 18 21 52" src="https://user-images.githubusercontent.com/7649772/211170784-1f6d4404-4ca1-4562-bdb5-7cbde44408af.png">

## Question

1) Is this behaviour expected? I'm aware that Astro behaves a little differently with spaces than what I expect from files like JSX. I'm wondering if this is somehow the default behaviour of `<slot />`.

2) Is there a simple way around it?

**Comment by JulianCataldo** [comment]
Hello :)

I recall that Astro is aligned with HTML regarding spaces, not JSX. Not 100% sure though.
It's tricky: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace.
That's probably why JSX strips phantom spaces for convenience, with a trade-off: `{' '}` has to be used when we want to add one explicitly, so the parser is kept away from stripping them.


A possible fix could be:
```astro
<a
  {...extraAttrs}><slot />{/* */}</a
>
```

instead of:

```astro
<a
  {...extraAttrs}>
  <slot />
</a>
```

`{/* */}` is a "glue", used to trick Astro's Prettier, so it doesn't force us an additional space.

Thanks for catching this! Will try this fix ASAP.

**Comment by JulianCataldo** [comment]
Fixed by https://github.com/JulianCataldo/web-garden/commit/9e3641216f093507def9c2b8a3ab5abe776d4276
